/**
 * ============================================================================
 * AUTOGENERATED E2E TEST FILE - DO NOT MODIFY MANUALLY
 * ============================================================================
 *
 * This file is automatically generated based on the E2E test specifications.
 * Any manual changes will be overwritten by the automation.
 *
 * To modify these tests, update the specification files:
 * - /docs/E2E_TESTS.md (root-level testing philosophy and constraints)
 * - /packages/cli/E2E_TESTS.md (CLI-specific test specifications)
 *
 * Then run the /update-e2e-tests command to regenerate this file.
 * ============================================================================
 */

/**
 * E2E Test Utilities
 *
 * This module provides shared utilities for e2e tests, including
 * environment-based test filtering for mock vs real agent tests.
 */

import { chmodSync, existsSync, lstatSync, readdirSync, rmSync } from 'node:fs';

/**
 * When true, tests that require real AI agent execution should run.
 * Set ROVER_E2E_REAL_AGENT=true to enable real agent tests.
 *
 * Usage in tests:
 * ```ts
 * import { SKIP_REAL_AGENT_TESTS } from './e2e-utils';
 *
 * describe.skipIf(SKIP_REAL_AGENT_TESTS)('my real agent test', () => { ... });
 * ```
 */
export const REAL_AGENT_MODE = process.env.ROVER_E2E_REAL_AGENT === 'true';

/**
 * Condition for skipping tests that require real AI agent execution.
 * Use with vitest's skipIf:
 *
 * ```ts
 * describe.skipIf(SKIP_REAL_AGENT_TESTS)('requires real agent', () => { ... });
 * ```
 */
export const SKIP_REAL_AGENT_TESTS = !REAL_AGENT_MODE;

/**
 * Condition for skipping tests that only work with mock agents.
 * Use with vitest's skipIf when you want to run ONLY real agent tests:
 *
 * ```ts
 * describe.skipIf(SKIP_MOCK_TESTS)('mock-only test', () => { ... });
 * ```
 */
export const SKIP_MOCK_TESTS = REAL_AGENT_MODE;

const makeWritableForCleanup = (path: string) => {
  if (!existsSync(path)) {
    return;
  }

  const entry = lstatSync(path);
  if (entry.isDirectory()) {
    chmodSync(path, 0o700);
    for (const child of readdirSync(path)) {
      makeWritableForCleanup(`${path}/${child}`);
    }
    return;
  }

  if (!entry.isSymbolicLink()) {
    chmodSync(path, 0o600);
  }
};

export const cleanupE2ETestDir = (path: string) => {
  if (!existsSync(path)) {
    return;
  }

  makeWritableForCleanup(path);
  rmSync(path, { recursive: true, force: true });
};

/**
 * ============================================================================
 * AUTOGENERATED E2E TEST FILE - DO NOT MODIFY MANUALLY
 * ============================================================================
 *
 * To modify these tests, update the specification files:
 * - /docs/E2E_TESTS.md (root-level testing philosophy and constraints)
 * - /packages/cli/E2E_TESTS.md (CLI-specific test specifications)
 *
 * Then run the /update-e2e-tests command to regenerate this file.
 * ============================================================================
 */
